name: aws_kv_storage
description: A starting point for Amplify Dart packages.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/common/aws_kv_storage
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: "^3.0.0"

dependencies:
  amplify_core: ">=1.3.0 <1.4.0"
  aws_common: ^0.5.0+2
  built_collection: ^5.1.1
  built_value: ">=8.6.0 <8.7.0"
  drift: ">=2.11.0 <2.12.0"
  js: ^0.6.7

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.4.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  built_value_generator: 8.6.1
  drift_dev: ^2.11.0
  test: ^1.22.1
