name: amplify_datastore
description: The Amplify Flutter DataStore category plugin, providing a queryable, on-device data store.
version: 0.2.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_datastore
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
dependencies:
  flutter:
    sdk: flutter
  amplify_datastore_plugin_interface:
    hosted:
      url: http://localhost:8000
      name: amplify_datastore_plugin_interface
    version: any
  amplify_core:
    hosted:
      url: http://localhost:8000
      name: amplify_core
    version: any
  plugin_platform_interface: ^2.0.0
  meta: ^1.1.8
  collection: ^1.14.13
dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_datastore
        pluginClass: AmplifyDataStorePlugin
      ios:
        pluginClass: AmplifyDataStorePlugin
