name: amplify_codegen
description: Temporary codegen package for vNext.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  amplify_core:
  args: ^2.4.0
  aws_common:
  built_collection: ^5.1.1
  built_value: ">=8.6.0 <8.7.0"
  code_builder: 4.5.0
  collection: ^1.16.0
  convert: ^3.1.1
  crypto: ^3.0.2
  dart_style: 2.3.1
  gql: ^0.14.0
  graphs: ^2.1.0
  meta: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  smithy: any
  smithy_aws: any
  smithy_codegen: any

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.4.0
  built_value_generator: 8.6.1
  path: ^1.8.2
  test: ^1.22.1

executables:
  amplify_codegen:
