targets:
  $default:
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: true
      build_web_compilers:entrypoint:
        enabled: false
  debug:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/**/*.debug.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
  release:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/**/*.release.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O2
  workers:
    auto_apply_builders: false
    builders:
      worker_bee_builder:worker_library_builder:
        enabled: true
    dependencies:
      - amplify_auth_cognito_common:debug
      - amplify_auth_cognito_common:release
