name: amplify_auth_cognito_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  amplify_core: ^0.1.0
  aws_common: ^0.1.0
  aws_signature_v4: ^0.1.0
  built_collection: ^5.0.0
  built_value: ^8.0.0
  crypto: ^3.0.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  oauth2: ^2.0.0
  smithy:
    hosted: https://pub.dillonnys.com
    version: ^0.5.0
  smithy_aws:
    hosted: https://pub.dillonnys.com
    version: ^0.5.0
  worker_bee: ^0.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.3
  built_value_generator: 8.3.3
  json_serializable: ^6.1.6
  lints: ^2.0.0
  test: ^1.16.0
  worker_bee_builder:
    path: ../../worker_bee/worker_bee_builder
