name: amplify_service_clients
description: A starting point for Amplify Dart packages.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/service_clients/amplify_service_clients
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: "^3.0.0"

dependencies:
  amplify_core: ">=1.2.0 <1.3.0"

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.4.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  test: ^1.22.1
