name: amplify_core
description: The base package containing common types and utilities that are shared across the Amplify Flutter packages.
version: 1.3.1
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_core
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ^3.0.6

dependencies:
  async: ^2.10.0
  aws_common: ">=0.5.0+2 <0.6.0"
  aws_signature_v4: ">=0.4.0+2 <0.5.0"
  built_collection: ^5.0.0
  built_value: ">=8.6.0 <8.7.0"
  collection: ^1.15.0
  graphs: ^2.1.0
  intl: ">=0.18.0 <1.0.0"
  json_annotation: ">=4.8.1 <4.9.0"
  logging: ^1.0.0
  meta: ^1.7.0
  retry: ^3.1.0
  smithy: ">=0.5.0 <0.6.0"
  stack_trace: ^1.10.0
  uuid: ">=3.0.6 <=3.0.7"

dev_dependencies:
  amplify_lints: ">=3.0.0 <3.1.0"
  build_runner: ^2.4.0
  build_test: ^2.1.5
  build_version: ^2.1.1
  build_web_compilers: ^4.0.0
  built_value_generator: 8.6.1
  checks: ^0.2.2
  code_builder: 4.5.0
  code_excerpt_updater:
    git:
      url: https://github.com/dart-lang/site-shared
      path: packages/code_excerpt_updater
  jni: ^0.5.0
  jnigen: ^0.5.0
  json_serializable: 6.7.1
  path: any
  smithy_codegen: any
  test: ^1.22.1
