targets:
  $default:
    sources:
      exclude:
        - example/**
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: true
      build_web_compilers:entrypoint:
        enabled: false
      built_value_generator:built_value:
        generate_for:
          include:
            - lib/src/asf/asf_context_data.dart
            - lib/src/asf/asf_worker.dart
            - lib/src/flows/**/*.dart
            - lib/src/model/*.dart
            - lib/src/model/hosted_ui/*.dart
            - lib/src/model/session/cognito_sign_in_details.dart
            - lib/src/model/session/cognito_user_pool_tokens.dart
            - lib/src/sdk/**/model/**.dart
  debug:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/src/workers/*.debug.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
    dependencies:
      - $default
  release:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/src/workers/*.release.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O2
            - --define=dart.vm.product=true
    dependencies:
      - $default
  workers:
    auto_apply_builders: false
    builders:
      worker_bee_builder:worker_copy_builder:
        enabled: true
        generate_for:
          - lib/src/workers/*.debug.dart.js
          - lib/src/workers/*.debug.dart.js.map
          - lib/src/workers/*.release.dart.js
          - lib/src/workers/*.release.dart.js.map
    dependencies:
      - amplify_auth_cognito_dart:debug
      - amplify_auth_cognito_dart:release
