name: amplify_flutter
description: The top level Flutter package for the AWS Amplify libraries.
version: 0.2.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  amplify_storage_plugin_interface:
    hosted:
      url: http://localhost:8000
      name: amplify_storage_plugin_interface
    version: any
  amplify_analytics_plugin_interface:
    hosted:
      url: http://localhost:8000
      name: amplify_analytics_plugin_interface
    version: any
  amplify_auth_plugin_interface:
    hosted:
      url: http://localhost:8000
      name: amplify_auth_plugin_interface
    version: any
  amplify_datastore_plugin_interface:
    hosted:
      url: http://localhost:8000
      name: amplify_datastore_plugin_interface
    version: any
  amplify_api_plugin_interface:
    hosted:
      url: http://localhost:8000
      name: amplify_api_plugin_interface
    version: any
  amplify_core:
    hosted:
      url: http://localhost:8000
      name: amplify_core
    version: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  amplify_api:
    hosted:
      url: http://localhost:8000
      name: amplify_api
    version: any
  amplify_analytics_pinpoint:
    hosted:
      url: http://localhost:8000
      name: amplify_analytics_pinpoint
    version: any
  amplify_auth_cognito:
    hosted:
      url: http://localhost:8000
      name: amplify_auth_cognito
    version: any
  amplify_datastore:
    hosted:
      url: http://localhost:8000
      name: amplify_datastore
    version: any
  amplify_storage_s3:
    hosted:
      url: http://localhost:8000
      name: amplify_storage_s3
    version: any
flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify
        pluginClass: Amplify
      ios:
        pluginClass: Amplify
