name: aws_rum_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  amplify_auth_cognito_dart:
  amplify_core:
  aws_common:
  aws_signature_v4:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  smithy:
    hosted: https://pub.dillonnys.com
    version: ^0.5.0

dev_dependencies:
  build_runner: ^2.0.0
  built_value_generator: 8.3.3
  lints: ^2.0.0
  test: ^1.16.0
