name: goldens
description: Golden files for smithy-dart
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  aws_common: ">=0.4.0 <0.5.0"
  collection: ^1.17.1
  ffi: ^2.0.2
  git: ^2.2.0
  jni: ^0.4.0
  pub_semver: ^2.1.4
  smithy: ">=0.4.0+1 <0.5.0"
  yaml_edit: ^2.1.1

dependency_overrides: 
  aws_common:
    path: ../../aws_common
  aws_signature_v4:
    path: ../../aws_signature_v4
  smithy:
    path: ../smithy
  smithy_aws:
    path: ../smithy_aws
  smithy_codegen:
    path: ../smithy_codegen

dev_dependencies:
  args: ^2.3.1
  file: ^6.1.2
  glob: ^2.0.2
  jnigen: ^0.4.0
  lints: ^2.0.0
  path: any
  pubspec_parse: ^1.2.0
  smithy_codegen:
    path: ../smithy_codegen
  test: ^1.22.1
