name: amplify_authenticator_test
description: A set of a utilities for testing amplify_authenticator
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0-0 <4.0.0"
  flutter: ">=3.8.0-10.1.pre"

dependencies:
  amplify_authenticator: ">=1.0.0-next.4 <1.0.0-next.5"
  amplify_flutter: ">=1.0.0-next.5 <1.0.0-next.6"
  amplify_test:
    path: ../../amplify_test
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  amplify_lints:
    path: ../../amplify_lints
