[package]
name = "amplify_test_schemas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apollo-smith = "0.3.2"
arbitrary = { version = "1.2.3", features = ["derive"] }
