name: amplify_api
description: The Amplify Flutter API category plugin, supporting GraphQL and REST operations.
version: 0.2.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_api
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
dependencies:
  amplify_api_plugin_interface:
    hosted:
      url: http://localhost:8000
      name: amplify_api_plugin_interface
    version: any
  amplify_core:
    hosted:
      url: http://localhost:8000
      name: amplify_core
    version: any
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
dev_dependencies:
  amplify_lints:
    hosted:
      url: http://localhost:8000
      name: amplify_lints
    version: any
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_api
        pluginClass: AmplifyApiPlugin
      ios:
        pluginClass: AmplifyApiPlugin
