name: amplify_service_clients_example
description: An example app showcasing the amplify_service_clients package.
version: 1.0.0
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  amplify_service_clients:
    path: ../

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
