// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// WorkerBeeGenerator
// **************************************************************************

// Generated by worker_bee_builder.

export 'example.worker.vm.dart' if (dart.library.js) 'example.worker.js.dart';
