// Generated by worker_bee_builder.

import 'package:example/example.dart';
import 'package:worker_bee/worker_bee.dart';

final _workers = <String, WorkerBeeBuilder>{'MyWorker': MyWorker.create};
void main() => runHive(_workers);
