name: amplify_api_plugin_interface
description: The platform interface for the API module of Amplify Flutter.
version: 0.2.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_api_plugin_interface
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  amplify_core:
    hosted:
      url: http://localhost:8000
      name: amplify_core
    version: any
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  uuid: ^3.0.1
dev_dependencies:
  amplify_lints:
    hosted:
      url: http://localhost:8000
      name: amplify_lints
    version: any
  flutter_test:
    sdk: flutter
