name: e2e_benchmark
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  e2e_test:
    path: ../e2e_test

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.1.5
  build_web_compilers: ^3.2.3
  lints: ^2.0.0
  test: ^1.16.0
