name: amplify_analytics_plugin_interface
description: The platform interface for the analytics module of Amplify Flutter.
version: 0.2.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_analytics_plugin_interface
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  amplify_core:
    hosted:
      url: http://localhost:8000
      name: amplify_core
    version: any
  flutter:
    sdk: flutter
  meta: ^1.1.8
dev_dependencies:
  amplify_lints:
    hosted:
      url: http://localhost:8000
      name: amplify_lints
    version: any
  flutter_test:
    sdk: flutter
