targets:
  $default:
    sources:
      exclude:
        - example/**
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: true
      build_web_compilers:entrypoint:
        enabled: false
  debug:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/*.debug.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
  release:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/*.release.dart
          - web/*.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O2
            - --define=dart.vm.product=true
