name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0-0 <3.0.0'

dependencies:
  aws_common: ^0.2.0
  collection: ^1.16.0
  worker_bee:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.6
  lints: ^2.0.0
  worker_bee_builder:
    path: ../../worker_bee_builder
