name: actions
description: Dart wrapper for the GitHub Actions Node.js modules.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  js: ^0.6.7
  path: ^1.8.3

dev_dependencies:
  amplify_lints: ^3.0.0
  test: ^1.22.1
