name: Smithy Goldens
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00
defaults:
  run:
    shell: bash
permissions:
  contents: read
  pull-requests: write

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

      - name: Setup Dart
        uses: dart-lang/setup-dart@196f54580e9eee2797c57e85e289339f85e6779d # main
        with:
          sdk: stable

      - name: Get Packages
        working-directory: packages/smithy/goldens
        run: dart pub upgrade

      - id: check
        name: Check Version
        working-directory: packages/smithy/goldens
        run: dart tool/bump_version.dart

      - name: Setup Java
        if: ${{ steps.check.updated == 'true' }}
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: corretto
          java-version-file: .java-version

      - name: Setup Gradle
        if: ${{ steps.check.updated == 'true' }}
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
        with:
          gradle-version: wrapper

      - name: Bump Version
        if: ${{ steps.check.updated == 'true' }}
        run: dart tool/generate.dart --update

      - name: Create Branch
        if: ${{ steps.check.updated == 'true' }}
        run: |
        set -e

        SMITHY_VERSION=${{ steps.check.smithyVersion }}
        BRANCH_NAME=chore/update-smithy-$SMITHY_VERSION
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m "chore(smithy): Bump version\n\nBumps version to $SMITHY_VERSION."
        git push -u origin $BRANCH_NAME

      - name: Create PR
        if: ${{ steps.check.updated == 'true' }}
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        with:
          script: |
          // Create pull request
          const { repo, owner } = context.repo;
          const smithyVersion = '${{ steps.check.smithyVersion }}';
          const branchName = `chore/update-smithy-${smithyVersion}`;
          await github.rest.pulls.create({
            title: 'chore(smithy): Bump version',
            owner,
            repo,
            head: branchName,
            base: 'next',
            body: [
              '> This PR is auto-generated by the `goldens` workflow: ' +
                '[packages/smithy/goldens/workflow.yaml](packages/smithy/goldens/workflow.yaml).',
              '',
              'Bumps version to ${smithyVersion}.',
            ].join('\n'),
          });
